# Site settings
title: a5
email: jase@jasecoop.com
description: > # Simple note taking
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://a5.gg" # the base hostname & protocol for your site
twitter_username: jasecoop
github_username:  jekyll

sass:
  sass_dir: _sass

# Build settings
markdown: kramdown
